### ISSUE TITLE
[NEW] Jitsi

### ISSUE THREAD

**Issue by tycrek** [tycrek/degoogle#112]
**Service name**: Jitsi

**Service URL**: https://jitsi.org/

**5/9/14 eyes?**: unknown

**Description**: Jitsi is an open-source secure video conferencing platform. No account is needed to use it, simply enter a Room Name to join or host a meeting. The host is able to kick rogue users from the call. Works directly in your browser, with apps available for iOS and Android. It is not necessary to self-host, but self-hosting is an option for those who wish to. Very low latency and easy to set up. A free public server is available at [meet.jit.si](https://meet.jit.si)

**Comment by virtadpt** [comment]
5/9/14 eyes?  Depends on where and how you set it up.

For what it's worth, meet.jit.si has two instances right now (13.248.156.98 and 76.223.28.75), both of which are in AWS, so they've got eyes like a potato on them.

**Comment by danarel** [comment]
It's a great alternative and works really well.

One point I try and make a lot is that for many people, "eyes" don't matter. For example:

Say I am Joe, and I am tired of using Google or Zoom because I don't want my personal information collected for advertising purposes. They have no reason to fear law enforcement spying on their chats, but that doesn't mean they don't care about privacy.

Yet, Jitsi, even if on AWS or even inside the US doesn't matter for their use.

On my personal privacy site, I list Fastmail as an email alternative. I hear a lot "they are in Australia!" which is valid. And if you're someone who knows their email CANNOT be seen by law enforcement, then they shouldn't use Fastmail (and probably not email at all!)

My longwinded point is, I think Jitsi is a great inclusion, because it puts privacy first. being in the 5/14 eyes or on AWS won't make it less privacy centric, it just means that some users will have to avoid it knowing that information.

**Comment by tycrek** [comment]
I agree. I could be wrong, but I think the only information AWS would be able to get from a user is their IP address. From there they could get a rough estimate of location and ISP, but I don't think it's enough to identify a user. Privacy concerned individuals can always use a VPN if there are concerns.

Part of why I decided to put unknown is because users are able to self-host. Since this is an option, there may be public or private servers outside the eyes, or the user can host their own instance outside the eyes.

I remember seeing something about Jitsi being end-to-end-encrypted but I can't find anything on their website. Can someone confirm if Jitsi video calls are E2EE?

**Comment by licaon-kter** [comment]
Fun fact, Jitsi Meet from F-Droid has no trackers either ;)
