### ISSUE TITLE
ONLYOFFICE & Cryptee Have Desktop Clients - Add them to "Docs/Sheets/Slides (offline)"

### ISSUE THREAD

**Issue by PalmoliveDev** [tycrek/degoogle#160]
As you can see in the links below, ONLYOFFICE and Cryptee have desktop clients. Please add them to "Docs/Sheets/Slides (offline)."

- [Cryptee](https://crypt.ee/download)
- [ONLYOFFICE](https://www.onlyoffice.com/download-desktop.aspx)

**Comment by tycrek** [comment]
### Cryptee

Cryptee does not have proper "downloads", at least in the traditional sense. From the link you provided:

> Cryptee is built for the web. You can simply start using Cryptee in your browser of choice.  
  We recommend Opera, Firefox, Google Chrome, or Safari for best compatibility and security.

With that said, they *do* provide a Progressive Web App which would work on Android and iOS, but I'm not sure if it works offline when run as a PWA. As for desktops:

> This allows you to start using Cryptee like a desktop app thanks to Google Chrome's latest Desktop Progressive Web Apps support.

The point of the guide is to avoid Google so I can't recommend this option.

### ONLYOFFICE

Looks good, I'll make a PR to add it.

**Comment by PalmoliveDev** [comment]
Thanks.

**Comment by johnozbay** [comment]
Hi there @tycrek! ✌🏻Maker of Cryptee here! 
First off – big fan of degoogle, thank you for all the good stuff! 

> I'm not sure if it works offline when run as a PWA. 
Yes it does. In fact on the landing page we talk about this : 
![image](https://user-images.githubusercontent.com/611338/84465321-64c9eb00-ac7f-11ea-9006-0736178fc1ff.png)

And for desktops, you can install it using _any_ desktop browser that supports PWA installations. So Brave, Edge etc all support installing it as well. However there are numerous bugs with their implementations, so we don't recommend it on the landing page to make our helpdesk's life easier. 

Otherwise, PWAs are even listed alongside regular apps in the Windows App Store:
https://medium.com/web-on-the-edge/progressive-web-apps-on-windows-8d8eb68d524e

On the desktop, the only exception is Firefox. And as for why not Firefox, seems like team FF didn't want to add this to desktop in the interest of "not duplicating the efforts by Microsoft / Windows" (comment 15 / last line) https://bugzilla.mozilla.org/show_bug.cgi?id=1407202#c15 😅

But from the looks of that thread, things are moving forward, and they're about to add it to desktop as well. 

On mobile pretty much all browsers allow PWA installations, Firefox, Opera, even Samsung Internet 😅

All in all PWAs are the best way to install apps. They're completely de-centralized, (or at least as decentralized as internet is) and you don't need any stores. You don't need approval for app updates in time-sensitive scenarios [like the way Apple blocked Telegram from releasing an update after pressure from Russia](https://www.theverge.com/2018/5/31/17412396/telegram-apple-app-store-app-updates-russia). Or you don't have to worry about your app getting pulled out from the store due to political pressure from China like the way [Apple pulled out the Quartz news app from their Chinese app store after its Hong Kong news coverage](https://www.cbsnews.com/news/apple-pulls-quartz-news-app-from-its-china-store-after-hong-kong-coverage/).

Hoping these make sense and help!
Best,
J

**Comment by woutfeys** [comment]
Alright, are we gonna add Cryptee?
