### ISSUE TITLE
[NEW] New alternative: TiddlyWiki for Google Keep

### ISSUE THREAD

**Issue by kg6gfq** [tycrek/degoogle#327]
| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: TiddlyWiki
  - **Alternative URL**: https://tiddlywiki.com/
  - **5/9/14 eyes**: unknown
  - **Description**: a personal note-taking system that can run in the browser as a single HTML file or as a NodeJS application.  It can be stored locally on a hard drive or removable drive, self-hosted on one's own server, or use various web-based storage options. 
- **FLOSS**
  - Repository: https://github.com/Jermolene/TiddlyWiki5
  - Active: yes
  - Download: Direct
  - Price: free
  - Self-host: yes
- **Encryption**
  - HTTPS: optionally?
  - E2EE: no
  - Modern Encryption: no
- **Transparency**
  - Public ownership: n/a? (community-maintained open source project, I believe)
  - 3rd-party audits: no
- **Privacy**
  - Anonymous payments: n/a (no payments)
  - Analytics: no
  - Captcha: rno
- **Extras**
  - .onion address: none
  - Warrant canary: no

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by virtadpt** [comment]
Can confirm.  Been using Tiddlywiki in my projects (and at work for documentation) since 2011.  You might want to add a note or a caveat that you'll need a browser extension to manipulate a Tiddlywiki normally because the "write directly to file and then re-read from it" functionality has been removed in pretty much every browser for a few years now.
