### ISSUE TITLE
Several alternatives you could include.

### ISSUE THREAD

**Issue by je-vv** [tycrek/degoogle#35]
For mobile mail client apps there's K9 and Fairmail, being K9 fairly used.

For calendar, besides mentioning [davdroid](https://www.davx5.com) you should also mention [icsdroid](https://icsx5.bitfire.at) both work together.

As phone OS, Something in between [LineageOS](https://lineageos.org) and [/e/](https://e.foundation), is [LineageOS for microG](https://lineage.microg.org).  LineageOS for microG is in essence Lineage with necessary changes to provide microG and all of its functionality.  Actually the /e/ is in essence Lineage for microG changing and adding default apps as well as its look and feel.

For mail service, calendar service, contacts service, and if you'd like also for Gogle Drive replacement, I'd also mention [/e/](https://e.foundation) and [nextCloud,](https://nextcloud.com) since Nextcloud is an open source self hosted cloud providing all those services and more, and there are 3rd parties offering Nextcloud service such as /e/, thus providing those services.

You don't mention camera, but [Open Camera](https://opencamera.sourceforge.io) is a good mobile app to keep in mind.

Related to mail clients, and for encryption purposes, I would also mention [OpenKeychain](https://www.openkeychain.org).

Finally I don't know if [popcorntime](https://popcorntime.sh) deserves being mentioned on TV and similar, since Kodi is also mentioned there...  Though not sure if it would imply mentioning some VPN services as well (you do mention you use PIA though).

**Comment by tycrek** [comment]
K9 and Fairmail are already listed as clients for Posteo. I'll update the line to be a bit more clear.

icsdroid looks good. Thanks for recommending it, I'll add it in.

I wasn't aware nextCloud had email. Thanks.

Open Camera looks good.

OpenKeychain looks good, but I'm not sure what section to put it in. Any suggestions @je-vv ?

Popcorn time looks interesting. I'll add it under Play Movies & TV but with a disclaimer since it does use torrenting which some countries or ISP's may not like.

Thanks for all the great suggestions!
