### ISSUE TITLE
[FIX] Remove PrivacyTools and replace with PrivacyGuide

### ISSUE THREAD

**Issue by danarel** [tycrek/degoogle#414]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

PrivacyGuide

### Error

PrivacyTools is no longer maintained by team, taken over by original owner of domain.

### Proposed changes

List PrivacyGuide.org instead. This is the new site maintained by the original team at PrivacyTools.

**Comment by tycrek** [comment]
Are you sure that's the right site? Going to https://www.privacyguide.org/ brings me to a Namecheap parking page. Is there any Issues or public discussion about the takeover?

**Comment by danarel** [comment]
Good catch!

https://privacyguides.org/

**Comment by danarel** [comment]
And here is what is going on:

https://twitter.com/privacy_guides/status/1443633412800225280

**Comment by tycrek** [comment]
Wow quite the read, will get it updated!

**Comment by dngray** [comment]
> Are you sure that's the right site? Going to https://www.privacyguide.org/ brings me to a Namecheap parking page. Is there any Issues or public discussion about the takeover?

It wasn't a takeover, basically the whole team left for Privacy Guides, because the original author was gone for over a year. He didn't really contribute anything anyway to the site as we ran it for years 2016 onwards.

Regarding your commit I've left some feedback https://github.com/tycrek/degoogle/commit/ecf30817e68925dcd9adf21fb3da9d79d0d37349
